version: '2'
services:
  bubbleupnpserver:
    build: .
    image: icebear8/bubbleupnpserver:0.1-r2
    container_name: bubbleUpnpServer
    restart: always
    network_mode: "host"
    ports:
      - "58050:58050"
    env_file:
      - ./config/default.env