version: '2'
services:
  tinkerforge:
    build: .
    image: icebear8/tinkerforge:0.2
    container_name: tinkerforge
    volumes:
    - ./config:/opt/tinkermqtt/config:ro
    restart: always
    env_file:
      - ./config/default.env
