version: '2'
services:
  nginx:
    build: .
    image: icebear8/nginx
    container_name: nginx
    ports:
    - "8080:8080"
    volumes:
    - ./config:/etc/nginx/sites-enabled
    restart: always